import kotlin.String

/**
 * Generated by [gradle-kotlin-dsl-libs](https://github.com/jmfayard/gradle-kotlin-dsl-libs)
 *
 * Run again
 *   `$ ./gradlew syncLibs`
 * to update this file */
object Versions {
    /**
     * [android-driver website](https://github.com/square/sqldelight/) */
    const val android_driver: String = "1.0.0-rc2" // up-to-date

    /**
     * [runner website](https://developer.android.com/testing) */
    const val androidx_test_runner: String = "1.1.0-alpha4" // available milestone: "1.1.0-beta02" 

    /**
     * [api website](https://github.com/ansman/kotshi) */
    const val api: String = "1.0.4" // available milestone: "1.0.5" 

    /**
     * [appcompat website](http://developer.android.com/tools/extras/support-library.html) */
    const val appcompat: String = "1.0.0" // up-to-date

    /**
     * [browser website](http://developer.android.com/tools/extras/support-library.html) */
    const val browser: String = "1.0.0" // up-to-date

    /**
     * [bugsnag-android website](https://bugsnag.com) */
    const val bugsnag_android: String = "4.2.2" // available milestone: "4.8.2" 

    const val byteunits: String = "0.9.1" // up-to-date

    /**
     * [gradle website](https://developer.android.com/studio) */
    const val com_android_tools_build_gradle: String = "3.3.0-alpha13" // up-to-date

    /**
     * [runtime website](https://github.com/square/sqldelight/) */
    const val com_squareup_sqldelight_runtime: String = "1.0.0-rc2" // up-to-date

    /**
     * [constraintlayout website](http://tools.android.com) */
    const val constraintlayout: String = "1.1.3" // available milestone: "2.0.0-alpha2" 

    /**
     * [converter-moshi website](https://github.com/square/retrofit/) */
    const val converter_moshi: String = "2.4.0" // up-to-date

    /**
     * [core-ktx website](http://developer.android.com/tools/extras/support-library.html) */
    const val core_ktx: String = "1.0.0" // up-to-date

    /**
     * [dagger website](https://github.com/google/dagger) */
    const val dagger: String = "2.16" // available milestone: "2.17" 

    /**
     * [dagger-android website](https://github.com/google/dagger) */
    const val dagger_android: String = "2.16" // available milestone: "2.17" 

    /**
     * [dagger-android-processor website](https://github.com/google/dagger) */
    const val dagger_android_processor: String = "2.16" // up-to-date

    /**
     * [dagger-compiler website](https://github.com/google/dagger) */
    const val dagger_compiler: String = "2.16" // available milestone: "2.17" 

    const val gradle_node_plugin: String = "1.2.0" // up-to-date

    /**
     * [gradle-plugin website](https://github.com/square/sqldelight/) */
    const val gradle_plugin: String = "1.0.0-rc2" // up-to-date

    const val jmfayard_github_io_gradle_kotlin_dsl_libs_gradle_plugin: String =
            "0.2.4" // exceed the version found: 0.2.3

    /**
     * [kotlin-android-extensions website](https://kotlinlang.org/) */
    const val kotlin_android_extensions: String = "1.3.0-rc-146" // up-to-date

    /**
     * [kotlin-android-extensions-runtime website](https://kotlinlang.org/) */
    const val kotlin_android_extensions_runtime: String = "1.3.0-rc-146" // up-to-date

    /**
     * [kotlin-annotation-processing-gradle website](https://kotlinlang.org/) */
    const val kotlin_annotation_processing_gradle: String = "1.3.0-rc-146" // up-to-date

    /**
     * [kotlin-argparser website](https://github.com/xenomachina/kotlin-argparser) */
    const val kotlin_argparser: String = "2.0.5" // available milestone: "2.0.7" 

    const val kotlin_frontend_plugin: String = "0.0.37" // up-to-date

    /**
     * [kotlin-gradle-plugin website](https://kotlinlang.org/) */
    const val kotlin_gradle_plugin: String = "1.3.0-rc-146" // up-to-date

    /**
     * [kotlin-scripting-compiler-embeddable website](https://kotlinlang.org/) */
    const val kotlin_scripting_compiler_embeddable: String = "1.3.0-rc-146" // up-to-date

    /**
     * [kotlin-serialization website](https://kotlinlang.org/) */
    const val kotlin_serialization: String = "1.3.0-rc-146" // up-to-date

    /**
     * [kotlin-serialization-unshaded website](https://kotlinlang.org/) */
    const val kotlin_serialization_unshaded: String = "1.3.0-rc-146" // up-to-date

    /**
     * [kotlin-stdlib website](https://kotlinlang.org/) */
    const val kotlin_stdlib: String = "1.3.0-rc-146" // up-to-date

    /**
     * [kotlin-stdlib-common website](https://kotlinlang.org/) */
    const val kotlin_stdlib_common: String = "1.3.0-rc-146" // up-to-date

    /**
     * [kotlin-stdlib-js website](https://kotlinlang.org/) */
    const val kotlin_stdlib_js: String = "1.3.0-rc-146" // up-to-date

    /**
     * [kotlin-test-annotations-common website](https://kotlinlang.org/) */
    const val kotlin_test_annotations_common: String = "1.3.0-rc-146" // up-to-date

    /**
     * [kotlin-test-common website](https://kotlinlang.org/) */
    const val kotlin_test_common: String = "1.3.0-rc-146" // up-to-date

    /**
     * [kotlin-test-js website](https://kotlinlang.org/) */
    const val kotlin_test_js: String = "1.3.0-rc-146" // up-to-date

    /**
     * [kotlin-test-junit website](https://kotlinlang.org/) */
    const val kotlin_test_junit: String = "1.3.0-rc-146" // up-to-date

    /**
     * [kotlinx-coroutines-android website](https://github.com/Kotlin/kotlinx.coroutines) */
    const val kotlinx_coroutines_android: String = "0.30.2-eap13" // available milestone: "0.30.2" 

    /**
     * [kotlinx-coroutines-core website](https://github.com/Kotlin/kotlinx.coroutines) */
    const val kotlinx_coroutines_core: String = "0.30.2-eap13" // available milestone: "0.30.2" 

    /**
     * [kotlinx-coroutines-core-common website](https://github.com/Kotlin/kotlinx.coroutines) */
    const val kotlinx_coroutines_core_common: String =
            "0.30.2-eap13" // available milestone: "0.30.2" 

    /**
     * [kotlinx-coroutines-core-js website](https://github.com/Kotlin/kotlinx.coroutines) */
    const val kotlinx_coroutines_core_js: String = "0.30.2-eap13" // available milestone: "0.30.2" 

    const val kotlinx_serialization_runtime: String =
            "0.8.0-rc13" // available milestone: "0.8.2-rc13" 

    const val kotlinx_serialization_runtime_common: String =
            "0.8.0-rc13" // available milestone: "0.8.2-rc13" 

    const val kotlinx_serialization_runtime_js: String =
            "0.8.0-rc13" // available milestone: "0.8.2-rc13" 

    /**
     * [ktlint website](https://github.com/shyiko/ktlint) */
    const val ktlint: String = "0.22.0" // available milestone: "0.29.0" 

    const val ktlint_gradle: String = "5.0.0" // available milestone: "6.1.0" 

    /**
     * [lint-gradle website](https://developer.android.com/studio) */
    const val lint_gradle: String = "26.3.0-alpha13" // up-to-date

    /**
     * [logging-interceptor website](https://github.com/square/okhttp) */
    const val logging_interceptor: String = "3.11.0" // up-to-date

    /**
     * [material website](http://developer.android.com/tools/extras/support-library.html) */
    const val material: String = "1.0.0" // up-to-date

    /**
     * [moshi website](https://github.com/square/moshi) */
    const val moshi: String = "1.6.0" // available milestone: "1.7.0" 

    /**
     * [okhttp website](https://github.com/square/okhttp) */
    const val okhttp: String = "3.11.0" // up-to-date

    /**
     * [okio website](https://github.com/square/okio/) */
    const val okio: String = "2.0.0" // available milestone: "2.1.0" 

    /**
     * [recyclerview website](http://developer.android.com/tools/extras/support-library.html) */
    const val recyclerview: String = "1.0.0" // up-to-date

    /**
     * [retrofit website](https://github.com/square/retrofit/) */
    const val retrofit: String = "2.4.0" // up-to-date

    /**
     * [retrofit2-kotlin-coroutines-adapter website](https://github.com/JakeWharton/retrofit2-kotlin-coroutines-adapter/) */
    const val retrofit2_kotlin_coroutines_adapter: String = "0.9.2" // up-to-date

    /**
     * [retrofit2-kotlinx-serialization-converter website](https://github.com/JakeWharton/retrofit2-kotlinx-serialization-converter/) */
    const val retrofit2_kotlinx_serialization_converter: String = "0.1.0" // up-to-date

    /**
     * [runtime-js website](https://github.com/square/sqldelight/) */
    const val runtime_js: String = "1.0.0-rc2" // up-to-date

    /**
     * [runtime-jvm website](https://github.com/square/sqldelight/) */
    const val runtime_jvm: String = "1.0.0-rc2" // up-to-date

    /**
     * [runtime-metadata website](https://github.com/square/sqldelight/) */
    const val runtime_metadata: String = "1.0.0-rc2" // up-to-date

    /**
     * [compiler website](https://github.com/ansman/kotshi) */
    const val se_ansman_kotshi_compiler: String = "1.0.4" // available milestone: "1.0.5" 

    /**
     * [sqlite-framework website](https://developer.android.com/topic/libraries/architecture/index.html) */
    const val sqlite_framework: String = "1.0.0" // available milestone: "2.0.0" 

    const val timber_android: String = "5.0.0-SNAPSHOT" 
            /* Could not find any version that matches com.jakewharton.timber:timber-android:+.
            Versions rejected by component selection rules: 5.0.0-SNAPSHOT
            Searched in the following locations:
              - https://repo.maven.apache.org/maven2/com/jakewharton/timber/timber-android/maven-metadata.xml 
            .... */

    const val timber_common: String = "5.0.0-SNAPSHOT" 
            /* Could not find any version that matches com.jakewharton.timber:timber-common:+.
            Versions rejected by component selection rules: 5.0.0-SNAPSHOT
            Searched in the following locations:
              - https://repo.maven.apache.org/maven2/com/jakewharton/timber/timber-common/maven-metadata.xml 
            .... */

    const val timber_jdk: String = "5.0.0-SNAPSHOT" 
            /* Could not find any version that matches com.jakewharton.timber:timber-jdk:+.
            Versions rejected by component selection rules: 5.0.0-SNAPSHOT 
            .... */

    const val timber_js: String = "5.0.0-SNAPSHOT" 
            /* Could not find any version that matches com.jakewharton.timber:timber-js:+.
            Versions rejected by component selection rules: 5.0.0-SNAPSHOT 
            .... */

    /**
     * [truth website](http://github.com/google/truth) */
    const val truth: String = "0.42" // up-to-date

    /**
     *
     *   To update Gradle, edit the wrapper file at path:
     *      ./gradle/wrapper/gradle-wrapper.properties
     */
    object Gradle {
        const val runningVersion: String = "4.10.1"

        const val currentVersion: String = "4.10.2"

        const val nightlyVersion: String = "5.1-20181015235836+0000"

        const val releaseCandidate: String = ""
    }
}
